# Site settings
baseurl = "https://charliecrowe.me/"
languageCode = "en-us"
title = "Charlie Crowe Portfolio"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-XXXXXXXX-Y"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "Charlie Crowe"
    subtitle = "Selected Works"
    author = "Laura Streb"
    description = "Charlie Crowe - an architecture portfolio"
    keywords = "Charlie, Charlie Crowe, architecture, portfolio"

    # Body background color
    bodybgcolor = "#f9f9f9"

    # Preview container button text
    buttontext = "See more"

    # Footer text
    footertext = ""

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']
    custom_css = ['css/theme-overrides.css']
